import type { Metadata, Viewport } from "next";
import {
 Cardo,
 DM_Sans,
 DM_Serif_Display,
 Lora,
 Noto_Naskh_Arabic,
 Noto_Sans,
 Noto_Sans_Arabic,
 Noto_Sans_Devanagari,
 Noto_Sans_Georgian,
 Noto_Serif,
 Noto_Serif_Georgian,
} from "next/font/google";
import { headers } from "next/headers";
import "./globals.css";
import { AnalyticsTracker } from "@/components/analytics/AnalyticsTracker";
import { AppThemeController } from "@/components/theme/AppThemeController";
import { NowPlayingBar } from "@/components/prayers/NowPlayingBar";
import { PrayerSyncBridge } from "@/components/profile/PrayerSyncBridge";
import { ProfilePrefsBridge } from "@/components/profile/ProfilePrefsBridge";
import { RouteExitBridge } from "@/components/nav/RouteExitBridge";
import { UpdateBridge } from "@/components/update/UpdateBridge";
import { NativeBridge } from "@/components/native/NativeBridge";
import { CommandPaletteMount } from "@/components/search/CommandPaletteMount";
import { FirstRunGate } from "@/components/onboarding/FirstRunGate";
import { SITE_URL } from "@/lib/site";
import { getServerLocale } from "@/lib/i18n/server";
import { getMessages } from "@/lib/i18n";
import { getLocale } from "@/lib/i18n/locales";
import { MessagesProvider } from "@/components/i18n/MessagesProvider";
import { LocaleBootstrap } from "@/components/i18n/LocaleBootstrap";
import { NONCE_HEADER } from "@/lib/security/headers";
import { IS_STATIC_EXPORT } from "@/lib/platform/buildTarget";

const dmSans = DM_Sans({
 variable: "--font-dm-sans",
 subsets: ["latin", "latin-ext"],
 display: "swap",
});

const dmSerif = DM_Serif_Display({
 variable: "--font-dm-serif",
 subsets: ["latin", "latin-ext"],
 weight: "400",
 display: "swap",
});

const lora = Lora({
 variable: "--font-lora",
 subsets: ["latin", "latin-ext"],
 display: "swap",
 // Variable font, pulls 400 / 500 / 600 / 700 + italics.
});

// Beta 2.3 language patch: per-script fallbacks for the 21-locale UI.
// latin-ext above covers Turkish, Polish, Hungarian, Romanian diacritics.
// Everything below is preload: false on purpose: next/font still emits
// @font-face rules with unicode-range, so browsers download a script's
// files only when a page actually renders that script. Latin-script
// visitors pay nothing; the Android export bundles them all for offline.
const notoSansX = Noto_Sans({
 variable: "--font-noto-sans-x",
 subsets: ["cyrillic", "cyrillic-ext", "greek"],
 display: "swap",
 preload: false,
});

const notoSerifX = Noto_Serif({
 variable: "--font-noto-serif-x",
 subsets: ["cyrillic", "cyrillic-ext", "greek"],
 display: "swap",
 preload: false,
});

const notoSansArabic = Noto_Sans_Arabic({
 variable: "--font-noto-sans-arabic",
 subsets: ["arabic"],
 display: "swap",
 preload: false,
});

// Naskh (not Nastaliq) for Arabic and Urdu prose: Nastaliq's tall line
// boxes break the reader layout and its files are several times larger.
const notoNaskh = Noto_Naskh_Arabic({
 variable: "--font-noto-naskh",
 subsets: ["arabic"],
 display: "swap",
 preload: false,
});

const notoSansGeorgian = Noto_Sans_Georgian({
 variable: "--font-noto-sans-georgian",
 subsets: ["georgian"],
 display: "swap",
 preload: false,
});

const notoSerifGeorgian = Noto_Serif_Georgian({
 variable: "--font-noto-serif-georgian",
 subsets: ["georgian"],
 display: "swap",
 preload: false,
});

const notoSansDevanagari = Noto_Sans_Devanagari({
 variable: "--font-noto-sans-devanagari",
 subsets: ["devanagari"],
 display: "swap",
 preload: false,
});

// Cardo: a serif designed for biblical scholarship, covers polytonic Greek
// (U+1F00 to 1FFF) and Hebrew. Used only for the interlinear column.
const cardo = Cardo({
 variable: "--font-greek",
 subsets: ["latin", "greek", "greek-ext"],
 weight: ["400", "700"],
 style: ["normal", "italic"],
 display: "swap",
});

export const metadata: Metadata = {
 metadataBase: new URL(SITE_URL),
 title: {
 default: "Purify, Orthodox prayer, calendar, and Scripture",
 template: "%s | Purify",
 },
 description:
 "Daily prayer, the saint of the day, fasting status, and the Septuagint plus KJV with patristic commentary.",
 // Manifest is now generated by app/manifest.ts (typed, with shortcuts +
 // maskable icons). Next routes /manifest.webmanifest to that handler.
 manifest: "/manifest.webmanifest",
 appleWebApp: {
 capable: true,
 statusBarStyle: "black-translucent",
 title: "Purify",
 },
 applicationName: "Purify",
 keywords: [
 "Orthodox",
 "prayer",
 "Bible",
 "Septuagint",
 "patristic",
 "saints",
 "fasting",
 "calendar",
 "Jesus Prayer",
 ],
 authors: [{ name: "Purify Team" }],
 openGraph: {
 type: "website",
 siteName: "Purify",
 title: "Purify, Orthodox prayer, calendar, and Scripture",
 description:
 "Daily prayer, the saint of the day, fasting status, and the Septuagint plus KJV with patristic commentary.",
 url: "/",
 locale: "en_US",
 },
 twitter: {
 card: "summary_large_image",
 title: "Purify",
 description: "Find God's peace in prayer.",
 },
 alternates: {
 canonical: "/",
 },
};

export const viewport: Viewport = {
 themeColor: "#101013",
 colorScheme: "dark",
 // viewport-fit=cover lets the page extend under iOS notch / home-indicator,
 // and the new safe-area utilities in globals.css (.safe-pb / .safe-bottom)
 // keep the bottom tab bar from sitting under the home indicator on phones.
 viewportFit: "cover",
};

// Sets the palette before the first paint. Kept as a string literal rather
// than a function so nothing here depends on bundling order. The key and
// the valid ids mirror lib/reader/readingModes.ts; the try/catch matters
// because a blocked storage API must fall back to the default palette
// rather than throw before the app has rendered anything at all.
const THEME_PREPAINT = [
  "(function(){try{",
  "var t=localStorage.getItem('purify.reader.theme');",
  "if(t&&['candlelight','monastery','parchment'].indexOf(t)>-1){",
  "document.documentElement.setAttribute('data-reading-mode',t);}",
  "}catch(e){}})();",
].join("");

export default async function RootLayout({
 children,
}: Readonly<{
 children: React.ReactNode;
}>) {
 const localeCode = await getServerLocale();
 const localeRecord = getLocale(localeCode);
 // English rides in the client bundle (see MessagesProvider); passing it
 // here would serialize ~135 KB into every prerendered page twice. Only
 // non-English web requests (always dynamic, never exported) send their
 // catalog over the wire.
 const messages =
   localeCode === "en" ? undefined : getMessages(localeCode);
 // Per-request CSP nonce, set by middleware. The pre-paint theme script
 // below carries it, so strict-dynamic accepts that one inline script.
 // Skipped in the native static export (no request headers, and no CSP or
 // middleware there) so the root layout, and thus every page, can still be
 // statically rendered.
 const nonce = IS_STATIC_EXPORT
   ? undefined
   : (await headers()).get(NONCE_HEADER) ?? undefined;
 return (
 <html
 lang={localeCode}
 dir={localeRecord.dir}
 // The pre-paint scripts below set data-reading-mode (and, under /admin,
 // data-adm-theme) on this element before React hydrates, which is the
 // whole point of running them early. React sees attributes on <html> that
 // its server output did not have and warns. This is the documented escape
 // hatch for exactly that pattern, and it reaches this element's own
 // attributes only, never its subtree.
 suppressHydrationWarning
 className={`${dmSans.variable} ${dmSerif.variable} ${lora.variable} ${cardo.variable} ${notoSansX.variable} ${notoSerifX.variable} ${notoSansArabic.variable} ${notoNaskh.variable} ${notoSansGeorgian.variable} ${notoSerifGeorgian.variable} ${notoSansDevanagari.variable} h-full antialiased`}
 >
 <body className="min-h-full flex flex-col">
 {/* Pre-paint. The palette lives in localStorage, which the server
     cannot read, so without this the first paint is always the default
     palette and a reader on Candlelight or Parchment gets a flash of
     the wrong one on every cold load. Runs before the body renders and
     is deliberately tiny and dependency-free. Carries the CSP nonce;
     the Android export has no nonce and needs none. */}
 <script
 nonce={nonce}
 dangerouslySetInnerHTML={{ __html: THEME_PREPAINT }}
 />
 <MessagesProvider locale={localeCode} messages={messages}>
 <AppThemeController />
 <LocaleBootstrap />
 {/* Root layout, for the same reason as NowPlayingBar below: Today sits
     outside the (app) group, so a bridge mounted in (app)/template.tsx
     would never clear the exit fade on a tap into Today. */}
 <RouteExitBridge />
 {/* Root layout, for the same reason. Today is app/page.tsx, outside the
     (app) group, and Today is where a reader prays the morning rule from.
     Mounted in (app)/layout.tsx this bridge never ran for them, so their
     prayer history was written locally and never pushed or pulled. */}
 <PrayerSyncBridge />
 {/* Same reason again: onboarding runs over Today, so the reader who states
     their interests and then signs in may never mount the (app) layout. */}
 <ProfilePrefsBridge />
 {/* And again: the app opens on Today, so an update prompt mounted in the
     (app) layout would never reach the reader who opens Purify, prays, and
     closes it, which is most of them. Renders nothing on the web, and
     nothing on native until lib/appUpdate/release.ts declares a
     versionCode above the installed one. */}
 <UpdateBridge />
 {children}
 {/* Root layout, not (app)/layout.tsx. Today is app/page.tsx, outside
     the (app) group, so a bar mounted there would unmount on every
     Today tap, which is exactly when a reader walks away from the
     player. Renders nothing until something is loaded. */}
 <NowPlayingBar />
 {/* And once more. This was in (app)/layout.tsx, so the palette did not
     exist on Today, which is the app's front door and the screen a phone
     reader returns to. Renders nothing until it is opened, and fetches
     the corpus only on that first open. */}
 <CommandPaletteMount />
 <FirstRunGate />
 </MessagesProvider>
 <AnalyticsTracker />
 <NativeBridge />
 </body>
 </html>
 );
}
