import type { Metadata, Viewport } from "next";
import { Cardo, DM_Sans, DM_Serif_Display, Lora } from "next/font/google";
import { headers } from "next/headers";
import "./globals.css";
import { AnalyticsTracker } from "@/components/analytics/AnalyticsTracker";
import { SITE_URL } from "@/lib/site";
import { getServerLocale } from "@/lib/i18n/server";
import { getMessages } from "@/lib/i18n";
import { getLocale } from "@/lib/i18n/locales";
import { MessagesProvider } from "@/components/i18n/MessagesProvider";
import { NONCE_HEADER } from "@/lib/security/headers";

const dmSans = DM_Sans({
 variable: "--font-dm-sans",
 subsets: ["latin"],
 display: "swap",
});

const dmSerif = DM_Serif_Display({
 variable: "--font-dm-serif",
 subsets: ["latin"],
 weight: "400",
 display: "swap",
});

const lora = Lora({
 variable: "--font-lora",
 subsets: ["latin"],
 display: "swap",
 // Variable font, pulls 400 / 500 / 600 / 700 + italics.
});

// Cardo: a serif designed for biblical scholarship, covers polytonic Greek
// (U+1F00 to 1FFF) and Hebrew. Used only for the interlinear column.
const cardo = Cardo({
 variable: "--font-greek",
 subsets: ["latin", "greek", "greek-ext"],
 weight: ["400", "700"],
 style: ["normal", "italic"],
 display: "swap",
});

export const metadata: Metadata = {
 metadataBase: new URL(SITE_URL),
 title: {
 default: "Purify, Orthodox prayer, calendar, and Scripture",
 template: "%s | Purify",
 },
 description:
 "Daily prayer, the saint of the day, fasting status, and the Septuagint plus KJV with patristic commentary.",
 // Manifest is now generated by app/manifest.ts (typed, with shortcuts +
 // maskable icons). Next routes /manifest.webmanifest to that handler.
 manifest: "/manifest.webmanifest",
 appleWebApp: {
 capable: true,
 statusBarStyle: "black-translucent",
 title: "Purify",
 },
 applicationName: "Purify",
 keywords: [
 "Orthodox",
 "prayer",
 "Bible",
 "Septuagint",
 "patristic",
 "saints",
 "fasting",
 "calendar",
 "Jesus Prayer",
 ],
 authors: [{ name: "Purify Team" }],
 openGraph: {
 type: "website",
 siteName: "Purify",
 title: "Purify, Orthodox prayer, calendar, and Scripture",
 description:
 "Daily prayer, the saint of the day, fasting status, and the Septuagint plus KJV with patristic commentary.",
 url: "/",
 locale: "en_US",
 },
 twitter: {
 card: "summary_large_image",
 title: "Purify",
 description: "Find God's peace in prayer.",
 },
 alternates: {
 canonical: "/",
 },
};

export const viewport: Viewport = {
 themeColor: "#161219",
 colorScheme: "dark",
 // viewport-fit=cover lets the page extend under iOS notch / home-indicator,
 // and the new safe-area utilities in globals.css (.safe-pb / .safe-bottom)
 // keep the bottom tab bar from sitting under the home indicator on phones.
 viewportFit: "cover",
};

export default async function RootLayout({
 children,
}: Readonly<{
 children: React.ReactNode;
}>) {
 const localeCode = await getServerLocale();
 const localeRecord = getLocale(localeCode);
 const messages = getMessages(localeCode);
 // Per-request CSP nonce, set by middleware. Read it so any future inline
 // <script nonce={nonce}> tags here will satisfy the strict-dynamic policy.
 // Currently unused by app code; Next's own runtime carries the nonce via
 // its build pipeline once the request header is set.
 const h = await headers();
 // eslint-disable-next-line @typescript-eslint/no-unused-vars
 const nonce = h.get(NONCE_HEADER) ?? undefined;
 return (
 <html
 lang={localeCode}
 dir={localeRecord.dir}
 className={`${dmSans.variable} ${dmSerif.variable} ${lora.variable} ${cardo.variable} h-full antialiased`}
 >
 <body className="min-h-full flex flex-col">
 <MessagesProvider locale={localeCode} messages={messages}>
 {children}
 </MessagesProvider>
 <AnalyticsTracker />
 </body>
 </html>
 );
}
