// Job 4 to 14: the first round of speeches. Eliphaz, Baldad and Sophar each
// speak, and Job answers each. Father lines are verbatim from St. Gregory the
// Great's Morals on the Book of Job (Oxford, 1844), held to the corpus by
// lib/walkthroughs/__tests__/job.test.ts.

import type { ChapterWalk } from "../types";

export const FIRST_ROUND: ChapterWalk[] = [
  {
    n: 4,
    title: "Can the pure perish?",
    movement: "first",
    cards: [
      {
        id: "job-4-5",
        verse: 5,
        title: "Praise that turns",
        hook: "Eliphaz begins by praising Job, and turns the praise into a rebuke.",
        body: "Eliphaz opens gently: Job has strengthened the weak and steadied failing knees, yet now that pain has touched him he is shaken. It is true, and it stings. Comfort that begins by reminding a sufferer of his own advice rarely comforts.",
        question: "When you are hurting, which reminders help, and which wound?",
        art: "friends",
      },
      {
        id: "job-4-7",
        verse: 7,
        title: "The friends' theory",
        hook: "Here is the belief all three friends share, and the book has already refuted it.",
        body: "The pure never perish, says Eliphaz, so suffering must uncover sin. The reader knows from chapter two that God called Job blameless. The friends' mistake is not cruelty. It is a small theology laid over a man they have not listened to.",
        question: "Where have you explained someone's pain before you understood it?",
        art: "scales",
        father: {
          verse: 7,
          index: 0,
          excerpt:
            "For if none that is innocent perished, the Prophet would not say, The righteous perisheth, and no man layeth it to heart.",
        },
      },
      {
        id: "job-4-17",
        verse: 17,
        title: "A true word, badly aimed",
        hook: "The voice in Eliphaz's night vision says something the Church also confesses.",
        body: "No mortal is pure before the Lord: the Church prays it too, for in God's sight no one living is justified (Psalm 142:2). It is true. But a true word thrown at a sufferer can still be the wrong word, at the wrong time, for the wrong man.",
        question: "What true thing have you said that did not help?",
        art: "lamp",
        father: {
          verse: 17,
          index: 0,
          excerpt:
            "Human righteousness compared with the righteousness of God is unrighteousness, for even a candle is seen to shine bright in the dark, but being set in the ray of the sun its light is darkened.",
        },
      },
    ],
    beats: [
      { id: "b1", text: "Eliphaz reminds Job how he once strengthened the weak.", verse: 3 },
      { id: "b2", text: "He asks who ever perished, being pure.", verse: 7 },
      { id: "b3", text: "He tells of lions whose strength is quenched.", verse: 10 },
      { id: "b4", text: "A spirit passes before his face in the night.", verse: 15 },
      { id: "b5", text: "A voice asks whether a mortal can be pure before the Lord.", verse: 17 },
    ],
    attribution: [
      {
        id: "a1",
        quote: "Remember then who has perished, being pure?",
        verse: 7,
        speaker: "eliphaz",
        choices: ["eliphaz", "job", "baldad"],
      },
      {
        id: "a2",
        quote: "Hast thou been often spoken to in distress?",
        verse: 2,
        speaker: "eliphaz",
        choices: ["job", "sophar", "eliphaz"],
      },
    ],
    prompt: "Eliphaz spoke true words at the wrong time. Write about a time the right words came, or did not.",
  },
  {
    n: 5,
    title: "Happy is the man God corrects",
    movement: "first",
    cards: [
      {
        id: "job-5-7",
        verse: 7,
        title: "Born to labour",
        hook: "Where the Hebrew has sparks flying upward, our Septuagint has young vultures seeking the heights.",
        body: "Eliphaz says trouble is our common lot: man is born to labour. Genesis says as much after the fall, bread by the sweat of the brow. The Septuagint's image adds a lift: the young of the vulture still seek the high places.",
        question: "What in you still reaches upward, even in a season of labour?",
        art: "wild",
        father: {
          verse: 7,
          index: 0,
          excerpt:
            "So then, ‘man is born to labour, and a bird to flying,’ for the mind flies free on high for the very same reason that the flesh toils the sorer below.",
        },
      },
      {
        id: "job-5-13",
        verse: 13,
        title: "The line St. Paul quoted",
        hook: "One sentence from Eliphaz's speech is quoted by St. Paul.",
        body: "St. Paul cites this line in 1 Corinthians 3:19: God takes the wise in their own craftiness. Much of what the friends say is true in itself. Their error is in the aim, not the words: sound sayings laid on a case they do not understand.",
        question: "Can a true saying be used unjustly? When have you seen it?",
        art: "gate",
      },
      {
        id: "job-5-17",
        verse: 17,
        title: "Discipline, and more than discipline",
        hook: "Eliphaz calls blessed the man God reproves. Scripture agrees, and the book adds a but.",
        body: "The Lord disciplines those He loves (Proverbs 3:12, Hebrews 12:6). But Eliphaz assumes Job needs correcting, and the book has told us otherwise. Discipline explains some suffering, never all of it, and never someone else's for certain.",
        question: "How do you tell correction from a trial you did not earn?",
        art: "tree",
        father: {
          verse: 17,
          index: 0,
          excerpt:
            "But they that are stricken, not for the cleansing of guilt, but for the testing of their fortitude, when they inquire into the causes of the stroke, must by no means be said to ‘reprove the correction of the Lord;’",
        },
      },
    ],
    beats: [
      { id: "b1", text: "Eliphaz says wrath destroys the foolish man.", verse: 2 },
      { id: "b2", text: "He says man is born to labour.", verse: 7 },
      { id: "b3", text: "He says he would call upon the Lord, the sovereign of all.", verse: 8 },
      { id: "b4", text: "He calls blessed the man the Lord reproves.", verse: 17 },
      { id: "b5", text: "He promises Job a grave like ripe corn reaped in its season.", verse: 26 },
    ],
    attribution: [
      {
        id: "a1",
        quote: "blessed is the man whom the Lord has reproved",
        verse: 17,
        speaker: "eliphaz",
        choices: ["job", "eliphaz", "lord"],
      },
      {
        id: "a2",
        quote: "Behold, we have thus sought out these matters",
        verse: 27,
        speaker: "eliphaz",
        choices: ["eliphaz", "sophar", "narrator"],
      },
    ],
    prompt: "Eliphaz offered answers before asking a single question. Write a question you would ask a friend who is suffering.",
  },
  {
    n: 6,
    title: "Weigh my grief",
    movement: "first",
    cards: [
      {
        id: "job-6-2",
        verse: 2,
        title: "Grief on a scale",
        hook: "Job does not ask to be excused, only to be weighed truly.",
        body: "Put my grief on a balance, Job says, and it would outweigh the sand of the sea. That is why his words have been rash. He is not asking for pity. He is asking for his burden to be measured before anyone rules on how he carries it.",
        question: "What have you carried that no one around you has really weighed?",
        art: "scales",
      },
      {
        id: "job-6-15",
        verse: 15,
        title: "The failing brook",
        hook: "Desert streams run full in winter and vanish in summer. So do some friends.",
        body: "In the desert a wadi roars in the rains and is dry stones by summer. Caravans from Thaema and Saba come looking for water and find nothing. Job's friends were full of words when he was well; now that he is parched, they have run dry.",
        question: "Who has stayed full for you in a dry season, and whom could you be that for?",
        art: "messengers",
        father: {
          verse: 15,
          index: 0,
          excerpt:
            "For a brook flows from the highlands down below, and while it gathers its waters from the winter rains, is dried up by the summer heats;",
        },
      },
      {
        id: "job-6-24",
        verse: 24,
        title: "Teach me",
        hook: "Job does not claim he cannot be wrong. He asks to be shown where.",
        body: "Teach me and I will be silent; if I have erred, tell me. Job is open to correction. What he refuses is a verdict without a reason. Humility is ready to be taught, and honesty will not confess a sin it cannot see.",
        question: "Is there a correction you would welcome, if someone would only explain it?",
        art: "friends",
        father: {
          verse: 24,
          index: 0,
          excerpt: "For pride begets hatred, humility only love.",
        },
      },
    ],
    beats: [
      { id: "b1", text: "Job asks for his grief to be weighed in a balance.", verse: 2 },
      { id: "b2", text: "He says the arrows of the Lord are in his body.", verse: 4 },
      { id: "b3", text: "He asks the Lord to wound him, but not destroy him utterly.", verse: 9 },
      { id: "b4", text: "He compares his friends to a brook that fails.", verse: 15 },
      { id: "b5", text: "He asks them to teach him where he has erred.", verse: 24 },
    ],
    attribution: [
      {
        id: "a1",
        quote: "Teach ye me, and I will be silent",
        verse: 24,
        speaker: "job",
        choices: ["job", "eliphaz", "lord"],
      },
      {
        id: "a2",
        quote: "Shall bread be eaten without salt?",
        verse: 6,
        speaker: "job",
        choices: ["eliphaz", "job", "baldad"],
      },
    ],
    prompt: "Job asked to be taught, not judged. Write one thing you would like God to teach you in a hard season.",
  },
  {
    n: 7,
    title: "What is man?",
    movement: "first",
    cards: [
      {
        id: "job-7-1",
        verse: 1,
        title: "Life as a trial",
        hook: "Our Septuagint calls human life a trial, a place of testing.",
        body: "Where the Hebrew speaks of hard service, like a soldier's, our Septuagint calls life a trial. The Fathers kept the image: the Christian life is a contest with a crown at its end (2 Timothy 4:7-8). Job feels only the contest, and cannot yet see the crown.",
        question: "What would change if you saw today's struggle as training rather than sentence?",
        art: "night",
      },
      {
        id: "job-7-17",
        verse: 17,
        title: "Psalm 8, inside out",
        hook: "Job asks the psalmist's question, what is man, as a complaint.",
        body: "Psalm 8 marvels that God is mindful of man. Job asks the same question and wishes God would look away. The attention that is glory in the psalm feels like scrutiny in pain. Hebrews 2 answers the psalm with Christ, crowned after tasting death for all.",
        question: "When has God's attention felt heavy, and when has it felt like care?",
        art: "stars",
        father: {
          verse: 20,
          index: 0,
          excerpt:
            "But blessed Job regarding these things, and seeking with groans wherefore they were so ordered, does not reproach justice, but interrogates mercy;",
        },
      },
      {
        id: "job-7-21",
        verse: 21,
        title: "Take away my sin",
        hook: "The blameless man ends by asking God to purge his sin.",
        body: "Blameless does not mean sinless. Job asks God to take away his iniquity, the prayer of every Christian. Even at his most bitter he speaks to God, not about Him, and he ends the chapter still waiting for an answer.",
        question: "What would you ask God to take away, if you asked plainly?",
        art: "altar",
        father: {
          verse: 21,
          index: 0,
          excerpt:
            "By which same words, what else is intimated but the desire of the expected Mediator, concerning Whom John saith, Behold the Lamb of God, Which taketh away the sin of the world.",
        },
      },
    ],
    beats: [
      { id: "b1", text: "Job calls human life a trial, like a hireling's days.", verse: 1 },
      { id: "b2", text: "He says his nights are full of pain until morning.", verse: 4 },
      { id: "b3", text: "He asks if he is a sea or a serpent, to be kept under watch.", verse: 12 },
      { id: "b4", text: "He asks what man is, that God should give him heed.", verse: 17 },
      { id: "b5", text: "He asks why God has not forgotten his iniquity.", verse: 21 },
    ],
    attribution: [
      {
        id: "a1",
        quote: "Am I a sea, or a serpent, that thou hast set a watch over me?",
        verse: 12,
        speaker: "job",
        choices: ["job", "wife", "eliphaz"],
      },
      {
        id: "a2",
        quote: "Is not the life of man upon earth a state of trial?",
        verse: 1,
        speaker: "job",
        choices: ["eliphaz", "job", "narrator"],
      },
    ],
    prompt: "Job kept talking to God even when he was angry. Write the sentence you would most like to say to Him today.",
  },
  {
    n: 8,
    title: "Ask the former generation",
    movement: "first",
    cards: [
      {
        id: "job-8-4",
        verse: 4,
        title: "The children's sins",
        hook: "Baldad says Job's children died for their own sins. The book never says so.",
        body: "Baldad goes further than Eliphaz: if your sons sinned, God cast them away. The reader knows Job offered sacrifice for them each time (1:5), and that their deaths came in the devil's trial of Job. Cruelty can wear the clothes of doctrine.",
        question: "When has someone explained a loss in a way that made it heavier?",
        art: "altar",
      },
      {
        id: "job-8-8",
        verse: 8,
        title: "Asking the fathers",
        hook: "Baldad appeals to the wisdom of the ancestors, as the Church does. The difference is in how.",
        body: "Orthodox Christians also ask the former generation: we read the Fathers. But Baldad uses tradition as a stick, a set of sayings to close a case. The Fathers read Job the other way, as a man tested and found faithful.",
        question: "Do you hold tradition as a verdict to hand down, or as a light to walk by?",
        art: "gate",
        father: {
          verse: 9,
          index: 0,
          excerpt:
            "And so the generation of old is set before us to be inquired of, that the period of the present life may be shewn to pass away like a shadow;",
        },
      },
      {
        id: "job-8-21",
        verse: 21,
        title: "Laughter still to come",
        hook: "Baldad promises the sincere laughter and thanksgiving. He is more right than he knows.",
        body: "Baldad means it as a condition: be pure and God will restore you. In the end God does restore Job, but not because the friends were right. Their theory was wrong; their hope was not. Joy is promised, though not on their terms.",
        question: "What would it mean to hope for joy without bargaining for it?",
        art: "restored",
        father: {
          verse: 21,
          index: 0,
          excerpt:
            "For the ‘mouth’ of the righteous will then be ‘filled with laughing’ when the tears of their pilgrimage being done, their hearts shall be filled to the full with exulting in eternal joy.",
        },
      },
    ],
    beats: [
      { id: "b1", text: "Baldad asks how long Job will go on speaking.", verse: 2 },
      { id: "b2", text: "He says Job's sons were cast away for their transgression.", verse: 4 },
      { id: "b3", text: "He tells Job to ask the former generation.", verse: 8 },
      { id: "b4", text: "He asks whether the rush can flourish without water.", verse: 11 },
      { id: "b5", text: "He says God will fill the mouth of the sincere with laughter.", verse: 21 },
    ],
    attribution: [
      {
        id: "a1",
        quote: "Will the Lord be unjust when he judges",
        verse: 3,
        speaker: "baldad",
        choices: ["baldad", "eliphaz", "job"],
      },
      {
        id: "a2",
        quote: "for we are of yesterday, and know nothing",
        verse: 9,
        speaker: "baldad",
        choices: ["job", "baldad", "sophar"],
      },
    ],
    prompt: "Baldad used old sayings to close a case. Write one truth of the faith that has opened a door for you instead.",
  },
  {
    n: 9,
    title: "A mediator between us",
    movement: "first",
    cards: [
      {
        id: "job-9-8",
        verse: 8,
        title: "Walking on the sea",
        hook: "Job praises the One who walks on the sea as on firm ground. The Gospels show Him doing it.",
        body: "Job's hymn to the Creator names things only God does: stretching out the heavens, treading the sea. When Christ walks on the water in Matthew 14, He does what Job says God alone does. The Church reads such lines as quiet witnesses to who Christ is.",
        question: "Which storm in your life do you most need to see Him walk on?",
        art: "sea",
        father: {
          verse: 8,
          index: 0,
          excerpt:
            "Thus ‘the Lord treadeth upon the waves of the sea.’ For when the storms of persecution lift up themselves, they are dashed in pieces in astonishment at His miracles.",
        },
      },
      {
        id: "job-9-11",
        verse: 11,
        title: "Grace that looks like wrath",
        hook: "God passes by and Job cannot see Him. Gregory says we often misread even what we do see.",
        body: "God passes by and Job does not see Him. Faith often lives here: unable to trace God's hand, unsure whether a trial is punishment or gift. The Fathers counsel humility about our own readings of providence, since what humbles us may be mercy.",
        question: "Is there something you called a punishment that may have been a gift?",
        art: "night",
        father: {
          verse: 11,
          index: 0,
          excerpt:
            "Thus, often that is the gift of grace which it takes to be wrath, and often that is the wrath of God's severity, which it supposes to be grace.",
        },
      },
      {
        id: "job-9-33",
        verse: 33,
        title: "Where is the mediator?",
        hook: "Job wishes for someone to stand between him and God. The Church knows His name.",
        body: "Job has argued that no mortal can win a case with God. So he longs for a mediator who could hear both sides. The Church confesses this One: Jesus Christ, God and man, the one mediator between God and men (1 Timothy 2:5).",
        question: "What would you say to God if you knew Someone stood beside you as you said it?",
        art: "redeemer",
        father: {
          verse: 32,
          index: 0,
          excerpt:
            "For before Him there never was forthcoming One, Who interceded for the guiltinesses of others in such wise, as not to have any of His own.",
        },
      },
    ],
    beats: [
      { id: "b1", text: "Job asks how a mortal can be just before the Lord.", verse: 2 },
      { id: "b2", text: "He praises the One who walks on the sea as on firm ground.", verse: 8 },
      { id: "b3", text: "He says God passes by him unseen.", verse: 11 },
      { id: "b4", text: "He says his days have fled away, swifter than a courier.", verse: 25 },
      { id: "b5", text: "He wishes a mediator were present between them.", verse: 33 },
    ],
    attribution: [
      {
        id: "a1",
        quote: "Would that he our mediator were present",
        verse: 33,
        speaker: "job",
        choices: ["baldad", "job", "eliphaz"],
      },
      {
        id: "a2",
        quote: "Who alone has stretched out the heavens, and walks on the sea as on firm ground.",
        verse: 8,
        speaker: "job",
        choices: ["lord", "job", "eliphaz"],
      },
    ],
    prompt: "Job longed for someone to stand between him and God. Write what you would bring to Christ, who stands there for you.",
  },
  {
    n: 10,
    title: "Thy hands have formed me",
    movement: "first",
    cards: [
      {
        id: "job-10-4",
        verse: 4,
        title: "Do You see as we see?",
        hook: "Job asks whether God looks at him the way people do. The friends did. God does not.",
        body: "Job's friends judged by appearances: great loss must mean great sin. Job asks whether God, too, sees only the surface. The answer the book gives is no. God sees the heart (1 Samuel 16:7), and He has already named Job blameless.",
        question: "How do you think God sees you, and where did you learn to see yourself that way?",
        art: "lamp",
      },
      {
        id: "job-10-9",
        verse: 9,
        title: "Made as clay",
        hook: "Job reminds God that He shaped him like clay. It is a protest and a prayer at once.",
        body: "Job appeals to God as his Maker: You formed me, clothed me with skin, gave me life and mercy (10:8-12). He does not doubt God made him with care. He cannot understand why the Maker would unmake His own work. Prayer can hold both.",
        question: "What would you say to God if you began with the words, You made me?",
        art: "ashheap",
        father: {
          verse: 9,
          index: 0,
          excerpt: "And hence in the eye of the Judge this frailty of the flesh alone is a ground for shewing pity;",
        },
      },
      {
        id: "job-10-21",
        verse: 21,
        title: "The land of darkness",
        hook: "Job asks for a little rest before the land of darkness. Christ would go down into that land.",
        body: "Job pictures death as a land of darkness with no return. He cannot yet see past it. At Pascha the Church sings that Christ went down into that very land and trampled down death by death, opening it from within.",
        question: "What darkness do you most need Christ to enter with you?",
        art: "night",
      },
    ],
    beats: [
      { id: "b1", text: "Job says he will speak in the bitterness of his soul.", verse: 1 },
      { id: "b2", text: "He asks God whether He sees as a mortal sees.", verse: 4 },
      { id: "b3", text: "He reminds God that He made him as clay.", verse: 9 },
      { id: "b4", text: "He asks why he was brought out of the womb.", verse: 18 },
      { id: "b5", text: "He asks for rest before he goes to the land of darkness.", verse: 21 },
    ],
    attribution: [
      {
        id: "a1",
        quote: "Remember that thou hast made me as clay",
        verse: 9,
        speaker: "job",
        choices: ["eliphaz", "job", "sophar"],
      },
      {
        id: "a2",
        quote: "Or dost thou see as a mortal sees?",
        verse: 4,
        speaker: "job",
        choices: ["job", "baldad", "lord"],
      },
    ],
    prompt: "Job began his prayer with 'Thy hands have formed me.' Write a prayer that starts from what God has made you.",
  },
  {
    n: 11,
    title: "Heaven is high",
    movement: "first",
    cards: [
      {
        id: "job-11-6",
        verse: 6,
        title: "The harshest friend",
        hook: "Sophar tells Job his suffering is a just recompense for his sins.",
        body: "Sophar is the bluntest of the three. He has not heard Job's case, yet he is sure of the verdict: what came to you is a just recompense. The Gospel refuses this arithmetic. Christ said of the blind man, neither he nor his parents sinned (John 9:3).",
        question: "Whose suffering have you quietly blamed on them?",
        art: "scales",
      },
      {
        id: "job-11-7",
        verse: 7,
        title: "Past finding out",
        hook: "Sophar says God cannot be searched out. The Church agrees, and draws a gentler lesson.",
        body: "God is higher than heaven and deeper than Hades: the Fathers teach that His essence is beyond all knowing. But if God is beyond us, so are His judgments, and Sophar should have been slower to name Job's sin. Mystery calls for humility, not verdicts.",
        question: "Where has the mystery of God made you gentler with others?",
        art: "mine",
        father: {
          verse: 7,
          index: 0,
          excerpt: "What does he call ‘the footsteps of God,’ saving the lovingkindness of His visitation?",
        },
      },
      {
        id: "job-11-17",
        verse: 17,
        title: "Prayer like the morning star",
        hook: "Under the harsh words, Sophar makes a lovely promise: prayer rising like the morning star.",
        body: "Sophar's promise is conditional and misapplied, but its images are true to the life of prayer: trouble passing like a wave, prayer like the morning star, peace dawning out of anxiety. Scripture later gives that star a name: Christ, the bright and morning star (Revelation 22:16).",
        question: "What anxiety would you like peace to dawn out of?",
        art: "stars",
        father: {
          verse: 18,
          index: 0,
          excerpt:
            "but with the merciful Judge it often happens that this very sadness, which even weighs down the effect of prayer, intercedes for us the more piercingly.",
        },
      },
    ],
    beats: [
      { id: "b1", text: "Sophar says a man of many words should be answered.", verse: 2 },
      { id: "b2", text: "He tells Job a just recompense for his sins has come.", verse: 6 },
      { id: "b3", text: "He asks whether Job can find out the traces of the Lord.", verse: 7 },
      { id: "b4", text: "He tells Job to put iniquity far from his hands.", verse: 14 },
      { id: "b5", text: "He promises that Job's prayer will be as the morning star.", verse: 17 },
    ],
    attribution: [
      {
        id: "a1",
        quote: "Wilt thou find out the traces of the Lord?",
        verse: 7,
        speaker: "sophar",
        choices: ["sophar", "lord", "job"],
      },
      {
        id: "a2",
        quote: "thy prayer shall be as the morning star",
        verse: 17,
        speaker: "sophar",
        choices: ["eliphaz", "sophar", "baldad"],
      },
    ],
    prompt: "Sophar was certain about another man's sin. Write about a mystery in your own life you are learning to leave with God.",
  },
  {
    n: 12,
    title: "Ask the beasts",
    movement: "first",
    cards: [
      {
        id: "job-12-4",
        verse: 4,
        title: "The righteous mocked",
        hook: "Job names what has happened to him: a righteous and blameless man has become a laughingstock.",
        body: "Job uses the words the book opened with: righteous and blameless (1:1). He is not boasting. He is naming the injustice of being mocked for suffering. The Church sees the same pattern fulfilled in Christ, the Righteous One mocked on the Cross.",
        question: "Have you been mocked for something you did not choose? How did you carry it?",
        art: "friends",
        father: {
          verse: 3,
          index: 0,
          excerpt:
            "Now in order to correct their pride, he asserts that he is ‘not inferior’ to them, and lest he should transgress the limits of his own humility, he keeps to himself that he is superior to them;",
        },
      },
      {
        id: "job-12-7",
        verse: 7,
        title: "Ask the beasts",
        hook: "Job sends his friends to the animals: all creation knows the hand of the Lord made it.",
        body: "The friends appealed to the ancestors; Job appeals to creation itself. Beasts, birds, earth and sea all know that the Lord made them and holds every breath in His hand. Creation is a witness anyone can hear, if they will listen.",
        question: "What in creation has spoken to you of God lately?",
        art: "wild",
        father: {
          verse: 9,
          index: 0,
          excerpt:
            "in that every creature, when it is looked at, as it were utters a voice of its own, bearing witness by that mere form which it has.",
        },
      },
      {
        id: "job-12-22",
        verse: 22,
        title: "Light in the shadow of death",
        hook: "Job says God brings deep things out of darkness, and the shadow of death into light.",
        body: "Job's hymn to God's power is mostly about things overturned: counsellors, judges, kings, priests. But this line looks further. The Church hears in it what Christ fulfilled: on those sitting in the region and shadow of death, light has sprung up (Matthew 4:16).",
        question: "What in you is still waiting for His light?",
        art: "lamp",
      },
    ],
    beats: [
      { id: "b1", text: "Job asks if wisdom will die with his friends.", verse: 2 },
      { id: "b2", text: "He says a righteous and blameless man has become a mockery.", verse: 4 },
      { id: "b3", text: "He tells them to ask the beasts and the birds.", verse: 7 },
      { id: "b4", text: "He says the breath of every man is in the Lord's hand.", verse: 10 },
      { id: "b5", text: "He says God brings the shadow of death into light.", verse: 22 },
    ],
    attribution: [
      {
        id: "a1",
        quote: "So then ye alone are men, and wisdom shall die with you?",
        verse: 2,
        speaker: "job",
        choices: ["sophar", "job", "eliphaz"],
      },
      {
        id: "a2",
        quote: "But ask now the beasts, if they may speak to thee",
        verse: 7,
        speaker: "job",
        choices: ["job", "lord", "baldad"],
      },
    ],
    prompt: "Job read God's hand in creation. Write about a place where the world around you has spoken of Him.",
  },
  {
    n: 13,
    title: "I will plead before Him",
    movement: "first",
    cards: [
      {
        id: "job-13-4",
        verse: 4,
        title: "Bad physicians",
        hook: "Job calls his friends bad physicians, and says silence would have been their wisdom.",
        body: "The friends did well in chapter two, sitting in silence for seven days. Their trouble began when they spoke. Job asks for the silence back. Often the best comfort for someone suffering is presence, not explanation.",
        question: "Who needs your presence more than your advice this week?",
        art: "friends",
        father: {
          verse: 5,
          index: 0,
          excerpt:
            "For this reason the holy man, seeing that his friends were anxious to appear what they were not, charged them to hold their peace, that they might not appear what they were.",
        },
      },
      {
        id: "job-13-7",
        verse: 7,
        title: "Lying for God",
        hook: "Job warns his friends that defending God with falsehood is itself a sin.",
        body: "The friends think they are protecting God's honour by insisting Job must be guilty. Job warns them that God is not served by untruth, even untruth told in His defence. In the end God agrees with Job (42:7).",
        question: "Have you ever defended God in a way that was not true to Him?",
        art: "scales",
        father: {
          verse: 8,
          index: 0,
          excerpt:
            "For to ‘take the face of God’ is to assume His authority in the act of judging; and he as it were ‘strives to judge for God,’ who when he reproves the several weak points in another, does not feel weak in himself within from fellow-feeling.",
        },
      },
      {
        id: "job-13-15",
        verse: 15,
        title: "Toward God, not away",
        hook: "A line many know as 'though he slay me' reads differently in our Septuagint, and just as boldly.",
        body: "Many know this verse as 'though he slay me, yet will I trust in him.' Our Septuagint reads: though the Mighty One lay hand on me, I will speak and plead before Him. Either way Job does not walk away from God. He walks toward Him.",
        question: "What would it look like to bring your complaint to God instead of away from Him?",
        art: "altar",
      },
      {
        id: "job-13-16",
        verse: 16,
        title: "A line St. Paul borrowed",
        hook: "St. Paul quotes this line of our Septuagint word for word.",
        body: "St. Paul, writing from prison, borrows this exact line from the Greek Job: this shall turn to my salvation (Philippians 1:19). Like Job, he does not know how his trial will end, but he trusts it will serve his salvation.",
        question: "What trial are you trusting God to turn toward your salvation?",
        art: "restored",
      },
    ],
    beats: [
      { id: "b1", text: "Job says he will reason before the Lord.", verse: 3 },
      { id: "b2", text: "He calls his friends bad physicians.", verse: 4 },
      { id: "b3", text: "He asks if they utter deceit before the Lord.", verse: 7 },
      { id: "b4", text: "He says he will plead before God, whatever comes.", verse: 15 },
      { id: "b5", text: "He asks why God hides Himself from him.", verse: 24 },
    ],
    attribution: [
      {
        id: "a1",
        quote: "But ye are all bad physicians",
        verse: 4,
        speaker: "job",
        choices: ["job", "sophar", "eliphaz"],
      },
      {
        id: "a2",
        quote: "And this shall turn to me for salvation",
        verse: 16,
        speaker: "job",
        choices: ["job", "baldad", "narrator"],
      },
    ],
    prompt: "Job chose to speak to God rather than about Him. Write to Him directly about whatever you are carrying.",
  },
  {
    n: 14,
    title: "Hope for a tree",
    movement: "first",
    cards: [
      {
        id: "job-14-2",
        verse: 2,
        title: "A flower, a shadow",
        hook: "Job describes every human life: born of a woman, blooming like a flower, gone like a shadow.",
        body: "Scripture does not flatter us about our frailty. The Psalms say the same: man's days are as grass. But the One born of a woman in the fullness of time (Galatians 4:4) took this fragile life as His own, so it would not end in shadow.",
        question: "How does remembering that life is short change what you will do today?",
        art: "uz",
        father: {
          verse: 2,
          index: 0,
          excerpt:
            "For what are men, as born in the world, but a kind of flowers in a field? Let us stretch our interior eyes over the breadth of the present world, and, lo, it is filled as it were with as many flowers as there are human beings.",
        },
      },
      {
        id: "job-14-7",
        verse: 7,
        title: "Hope for a tree",
        hook: "Job says a felled tree has more hope than a man. The Church reads on to the Resurrection.",
        body: "Job envies the stump: cut down, it can still sprout at the scent of water, while a man who dies seems gone. The Church sees further. Christ, laid in the earth like a seed, rose as the first-fruits of all who sleep (1 Corinthians 15:20).",
        question: "Where do you need to believe that something cut down can grow again?",
        art: "tree",
      },
      {
        id: "job-14-14",
        verse: 14,
        title: "Shall he live again?",
        hook: "Job asks if the dead will live again, and for a moment he dares to hope so.",
        body: "Job asks the question every grieving heart asks: if a man dies, will he live again? He dares to hope God will call and he will answer. The Church answers with Christ's rising: the dead will hear the voice of the Son of God (John 5:25).",
        question: "Whom are you waiting to see again, and how does that hope shape today?",
        art: "redeemer",
        father: {
          verse: 15,
          index: 0,
          excerpt:
            "Then therefore we shall truly ‘answer God,’ Who ‘calleth,’ when at the bidding of the Supreme Incorruption we shall arise incorruptible;",
        },
      },
    ],
    beats: [
      { id: "b1", text: "Job says a mortal born of a woman is short-lived.", verse: 1 },
      { id: "b2", text: "He says there is hope for a tree that is cut down.", verse: 7 },
      { id: "b3", text: "He says man lies down in death until the heaven is dissolved.", verse: 12 },
      { id: "b4", text: "He asks whether a man who dies shall live again.", verse: 14 },
      { id: "b5", text: "He says God destroys the hope of man, as waters wear away stones.", verse: 19 },
    ],
    attribution: [
      {
        id: "a1",
        quote: "For there is hope for a tree",
        verse: 7,
        speaker: "job",
        choices: ["baldad", "job", "eliphaz"],
      },
      {
        id: "a2",
        quote: "For if a man should die, shall he live again",
        verse: 14,
        speaker: "job",
        choices: ["job", "sophar", "narrator"],
      },
    ],
    prompt: "Job wondered whether the dead would live again. Write what the Resurrection changes for you today.",
  },
];
